CREATE OR REPLACE FUNCTION AUTOGENKODEKAT(
    KODE VARCHAR2
)
RETURN VARCHAR
IS
    IDTEMP VARCHAR2(255);
    JUM NUMBER;
BEGIN
    SELECT NVL(CAST(MAX(SUBSTR(KODE_KAT,4,3)) AS INT),'0') + 1 INTO JUM FROM KATEGORI WHERE KODE_KAT LIKE '%' || KODE || '%';
    IDTEMP := KODE || LPAD(JUM, 3, '0');
    RETURN IDTEMP;
END;
/

CREATE OR REPLACE FUNCTION AUTOGENKODEMERK(
    KODE VARCHAR2
)
RETURN VARCHAR
IS
    IDTEMP VARCHAR2(255);
    JUM NUMBER;
BEGIN
    SELECT NVL(CAST(MAX(SUBSTR(KODE_MERK,4,3)) AS INT),'0') + 1 INTO JUM FROM MERK WHERE KODE_MERK LIKE '%' || KODE || '%';
    IDTEMP := KODE || LPAD(JUM, 3, '0');
    RETURN IDTEMP;
END;
/

CREATE OR REPLACE TRIGGER UPDATEKAT
BEFORE UPDATE ON KATEGORI
FOR EACH ROW
BEGIN
    FOR I IN(
        SELECT ID FROM BARANG WHERE KATEGORI = :OLD.KODE_KAT
    ) LOOP
        UPDATE BARANG
        SET KATEGORI = :NEW.KODE_KAT
        WHERE ID = I.ID;
    END LOOP;
END;
/

CREATE OR REPLACE TRIGGER UPDATEMERK
BEFORE UPDATE ON MERK
FOR EACH ROW
BEGIN
    FOR I IN(
        SELECT ID FROM BARANG WHERE MERK = :OLD.KODE_MERK
    ) LOOP
        UPDATE BARANG
        SET MERK = :NEW.KODE_MERK
        WHERE ID = I.ID;
    END LOOP;
    UPDATE GARANSI
    SET KODE_MERK = :NEW.KODE_MERK
    WHERE KODE_MERK = :OLD.KODE_MERK;
END;
/

CREATE OR REPLACE TRIGGER AUTOGENNOTA
BEFORE INSERT ON H_BELI
FOR EACH ROW
DECLARE
    NOMORNOTA VARCHAR2(255);
BEGIN
    SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') || LPAD(NVL(MAX(SUBSTR(NOMOR_NOTA, 9, 3)), '0') + 1, 3, '0') INTO NOMORNOTA
    FROM H_BELI WHERE NOMOR_NOTA LIKE TO_CHAR(SYSDATE, 'YYYYMMDD') || '%';
    :NEW.NOMOR_NOTA := NOMORNOTA;

    UPDATE CUSTOMER
    SET SALDO = SALDO - :NEW.TOTAL_PEMBELIAN
    WHERE ID = :NEW.ID_CUSTOMER;
END;
/

CREATE OR REPLACE TRIGGER UPDATESTOK
BEFORE INSERT ON D_BELI
FOR EACH ROW
DECLARE
    STOKLAMA INT;
    NOMORNOTA VARCHAR2(255);
BEGIN
    SELECT STOK INTO STOKLAMA FROM BARANG WHERE ID = :NEW.ID_BARANG;
    UPDATE BARANG
    SET STOK = STOKLAMA-:NEW.JUMLAH
    WHERE ID = :NEW.ID_BARANG;
    SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') || LPAD(NVL(MAX(SUBSTR(NOMOR_NOTA, 9, 3)), '0') + 1, 3, '0') INTO NOMORNOTA
    FROM D_BELI WHERE NOMOR_NOTA LIKE TO_CHAR(SYSDATE, 'YYYYMMDD') || '%';
    :NEW.NOMOR_NOTA := NOMORNOTA;
END;
/

COMMIT;