CREATE OR REPLACE FUNCTION AUTOGENKODEKAT(
    KODE VARCHAR2
)
RETURN VARCHAR
IS
    IDTEMP VARCHAR2(255);
    JUM NUMBER;
BEGIN
    SELECT NVL(CAST(MAX(SUBSTR(KODE_KAT,4,3)) AS INT),'0') + 1 INTO JUM FROM KATEGORI WHERE KODE_KAT LIKE '%' || KODE || '%';
    IDTEMP := KODE || LPAD(JUM, 3, '0');
    RETURN IDTEMP;
END;
/

CREATE OR REPLACE FUNCTION AUTOGENKODEMERK(
    KODE VARCHAR2
)
RETURN VARCHAR
IS
    IDTEMP VARCHAR2(255);
    JUM NUMBER;
BEGIN
    SELECT NVL(CAST(MAX(SUBSTR(KODE_MERK,4,3)) AS INT),'0') + 1 INTO JUM FROM MERK WHERE KODE_MERK LIKE '%' || KODE || '%';
    IDTEMP := KODE || LPAD(JUM, 3, '0');
    RETURN IDTEMP;
END;
/
